module Maquina
  class Credentials
    VERSION: String

    class MasterKeyMissing < StandardError
    end

    class DecryptionFailed < StandardError
    end

    def self.write: (Hash[untyped, untyped] hash, ?credentials_path: String? credentials_path) -> void

    def self.encrypt: (String payload, String raw_key) -> String

    def self.decrypt: (String encrypted, String raw_key) -> String

    def self.resolve_credentials_path: (?String? credentials_path) -> String

    def initialize: (?credentials_path: String? credentials_path) -> void

    def read: (String? path) -> String
  end
end
